### ISSUE TITLE
Hactoberfest Excluded Repository

### ISSUE THREAD

**Issue by Ukesh-dev** [kishanrajput23/Hacktoberfest-2022#158]
If you guys are trying to get swags by using this repo then this is totally useless as this repo is EXCLUDED.

**Comment by stenwire** [comment]
Do you happen to have a curated list of legit hacktoberfest 2022 repositories?

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
