### ISSUE TITLE
ANNOUNCEMENT - EXCLUDED REPOSITORY

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#181]
Hello folks, 
Please don't contribute in this repository because it has been excluded from Hacktoberfest 2022.

**Comment by NeoHBz** [comment]
what's the reason for this?

**Comment by theshubhamgour** [comment]
What should be done then?

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by maharshi-sinha** [comment]
I think non-code/low code contributors are getting this mail! Those who are actually contributing something aren't getting this kind of `exclusion` kinda thing, some of my fellow friends who have done the same kind of contribution like fixing grammatical mistakes, adding blogs, and stuff also get the same result! That's why I'm thinking that probably that must be the reason.
